"""add zip to Endereco

Revision ID: bd00aa136472
Revises: 107565750ac5
Create Date: 2025-06-09 16:31:46.625900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd00aa136472'
down_revision: Union[str, None] = '107565750ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enderecos', sa.Column('zip', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enderecos', 'zip')
    # ### end Alembic commands ###
